### ISSUE TITLE
Can't specify port in twistd plugin

### ISSUE THREAD

**Issue by jerith** [praekeltfoundation/vumi-http-proxy#15]
If I specify `--port=1234` to `twistd -n vumi_http_proxy`, I get the following error:

```
  File "/Users/jerith/code/vumi-http-proxy/vumi_http_proxy/servicemaker.py", line 33, in makeService
    options["port"], str(options["interface"])), factory)
TypeError: %d format: a number is required, not str
```

`makeService()` is expecting the port to be an integer (and the default value is an integer), but if it's specified on the command line the option value is a string.

**Comment by CarlaLlama** [comment]
Oh! Thanks, will get right on this
