### ISSUE TITLE
Include manual DNS lookup to find IP's

### ISSUE THREAD

**Issue by CarlaLlama** [praekeltfoundation/vumi-http-proxy#6]

**Comment by CarlaLlama** [comment]
https://twistedmatrix.com/trac/wiki/TwistedNames ?

**Comment by hodgestar** [comment]
That is for how to write a DNS _server_. Thankfully we don't need to do that. We only need to resolve names (i.e. a tiny part of what a DNS _client_ does). We can do that with `getHostByName` in `twisted.names.client` (see http://twistedmatrix.com/documents/current/api/twisted.names.client.html#getHostByName).

**Comment by rudigiesler** [comment]
(to avoid confusion) The link that @CarlaLlama posted covers both the server and the client.

**Comment by hodgestar** [comment]
Doh. :)

**Comment by CarlaLlama** [comment]
Cool! I saw the `getHostByName` and just assumed I'd need to implement all the other stuff, thanks for clarifying :)
